name: fresh_start
description: "A new Flutter project."
publish_to: "none"
version: 0.1.2

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  flutter_bloc: ^8.1.3
  get_it: ^8.0.0
  injectable: ^2.3.2
  go_router: ^14.0.0
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.2
  either_dart: ^1.0.0
  flutter_secure_storage: ^9.0.0
  auto_size_text: ^3.0.0
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  mask_text_input_formatter: ^2.8.0
  flutter_smart_dialog: ^4.9.6
  sentry_flutter: ^8.0.0
  internet_connection_checker_plus: ^2.3.0
  bloc_concurrency: ^0.2.5
  stream_transform: ^2.1.0
  amplitude_flutter: ^3.16.2
  device_info_plus: ^11.0.0
  package_info_plus: ^8.0.2
  flutter_in_store_app_version_checker:
    git:
      url: https://github.com/isafiulin/flutter_in_store_app_version_checker.git
      ref: main # branch name
  provider: ^6.1.2
  talker_flutter: ^4.1.5
  easy_localization: ^3.0.6
  intl: ^0.19.0
  path_provider: ^2.1.3
  share_plus: ^10.0.2
  flutter_screenutil: ^5.9.3
  firebase_core: ^3.0.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  cupertino_icons: ^1.0.8
  collection: ^1.18.0
  loader_overlay: ^4.0.2+1
  hydrated_bloc: ^9.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  build_runner: ^2.4.7
  injectable_generator: ^2.6.1
  dart_code_linter: ^1.1.3
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/svg/main_tab/
    - assets/images/
    - assets/translations/
